clc;
clear;
close all;

% Read the output generated by C
data = readtable('E:\DSP_toolkit\results\C_filtered_signal.csv');

t_c = data.time;
filtered_c = data.filtered;

% Generate the same signal
Fs = 1000;
N = 1000;

f1 = 50;
f2 = 200;

t = (0:N-1)' / Fs;

signal = sin(2*pi*f1*t) + 0.5*sin(2*pi*f2*t);

% Create the same FIR filter
filter_order = 20;
cutoff_frequency = 100;

normalized_cutoff = cutoff_frequency / (Fs/2);

h = fir1(filter_order, normalized_cutoff);

% MATLAB FIR filtering
matlab_filtered = filter(h, 1, signal);

% Plot comparison
figure;

plot(t_c, filtered_c, 'LineWidth', 1);
hold on;

plot(t, matlab_filtered, '--', 'LineWidth', 1);

xlabel('Time (seconds)');
ylabel('Amplitude');
title('C FIR vs MATLAB FIR');

legend('C Implementation', 'MATLAB');

grid on;
xlim([0 1]);
